### PR TITLE
web: fix tags not adding/removing in note header bar

### LINKED ISSUE #7485: Cannot add/delete Tags anymore (web / macos version)
Hello
Since a moment, I cannot add / delete tags anymore to notes. This only affects the web and macos versions for me, android works fine
- I CAN add and delete tags for themselves, but
- I cannot delete a tag in a note anymore
- I cannot add a tag in a note anymore: I can select the tag, but when I change to another note and come back to the note, the tag is not there anymore. In the tags list, however, the tag shows the right number of notes, but also the note linked is not shown. 

**Device information:**
App version: 3.0.25-6a9ddb7-web
OS: OS X 10.15.7 64-bit
Browser: Chrome 132.0.0.0
Pro: true

### LINKED ISSUE #7621: Desktop: Errors removing/updating tags on notes
Clicking the red x on a tag in a note does not remove the tag from the note on Desktop. Removing the same tag on the same note on mobile works, but has errors when updating on desktop; the note still shows the tag beneath the title, but when you click the tag to show all the tagged notes in the sidebar, the note in question does not appear.

Tagging notes seems to work intermittently on Desktop, too. Tagging a note appears to work (the tag shows on the note), but when you go to that tag in the sidebar, the note does not appear.

**Device information:**
App version: 3.0.26-2ab3218-desktop
OS: Windows 10 64-bit
Browser: Electron 31.7.4
Pro: true

### PR DESCRIPTION
**Pull request by 01zulfi**
Signed-off-by: 01zulfi <85733202+01zulfi@users.noreply.github.com>

Closes #7621 
Closes #7485

### CODE REVIEW

**Comment by thecodrr** [comment]
Thanks!

File: apps/web/src/components/editor/header.tsx [hunk 1]
```diff
@@ -31,19 +31,27 @@ import { MenuItem } from "@notesnook/ui";
...
-    (store) => store.getActiveSession(["default", "readonly"])?.tags
+  const activeSession = useEditorStore((store) =>
+    store.getActiveSession(["default", "readonly"])
   );
+  const tags = activeSession?.tags;
+  const noteId = activeSession?.note.id;
 
   const setTag = useCallback(async function (
-    noteId: string,
+    noteId: string | undefined,
```
Comment (thecodrr) [inline apps/web/src/components/editor/header.tsx:46]: No need for this. Just don't render the `Header` if `noteId` is `undefined`.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: apps/web/src/components/editor/header.tsx [hunk 2]
```diff
@@ -31,13 +31,16 @@ import { MenuItem } from "@notesnook/ui";
 import { navigate } from "../../navigation";
 import { Tag } from "@notesnook/core";
 import { strings } from "@notesnook/intl";
+import { showToast } from "../../utils/toast";
```
Comment (thecodrr) [inline apps/web/src/components/editor/header.tsx:34]:
```suggestion
```

File: apps/web/src/stores/editor-store.ts [hunk 3]
```diff
@@ -467,9 +467,13 @@ class EditorStore extends BaseStore<EditorStore> {
...
-            updateSession(event.item.toId, undefined, {
-              tags: await db.notes.tags(event.item.toId)
-            });
+            for (const session of sessions) {
+              if ("note" in session && session.note.id === event.item.toId) {
+                updateSession(session.id, undefined, {
+                  tags: await db.notes.tags(event.item.toId)
+                });
+              }
+            }
```
Comment (thecodrr) [inline apps/web/src/stores/editor-store.ts:476]: There's no need to loop over the sessions here. We are already looping over them above.
```suggestion
            updateSession(session.id, undefined, {
              tags: await db.notes.tags(event.item.toId)
            });
```

**Comment by thecodrr** [comment]
@01zulfi can you add tests for these? I think it's a basic enough functionality that should be tested.

File: apps/web/src/stores/editor-store.ts (hunk 3 above)
Comment (01zulfi) [reply apps/web/src/stores/editor-store.ts]: `session` is undefined here. We need to loop over the sessions

Comment (thecodrr) [reply apps/web/src/stores/editor-store.ts:476]: You're right. Can you also change it for colors a little bit above? I think it's also broken.

Comment (01zulfi) [reply apps/web/src/stores/editor-store.ts:480]: @thecodrr done

**Review by thecodrr — APPROVED** [review]
