### PR TITLE
web: fix links in report issue dialog

### LINKED ISSUE #7057: GitHub issue link in "Report an issue" dialog opens site inside Notesnook
The GitHub report link generated when reporting an issue is clickable and it opens the link inside the Notesnook window itself. This is bad because you get stuck there with no way out except to exit Notesnook entirely.

**Device information:**
App version: 3.0.22-7f2c8ca-desktop
OS: Windows 10 64-bit
Browser: Electron 31.7.4
Pro: true

### PR DESCRIPTION
**Pull request by 01zulfi**
Signed-off-by: 01zulfi <85733202+01zulfi@users.noreply.github.com>

Closes #7057

### CODE REVIEW

File: apps/web/src/utils/md.ts [hunk 1]
```diff
@@ -19,6 +19,22 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
...
+  const temp = document.createElement("div");
+  temp.innerHTML = html;
+  const elements = temp.querySelectorAll(tag);
+  elements.forEach((element) => {
+    Object.entries(attributes).forEach(([key, value]) => {
+      element.setAttribute(key, value);
+    });
+  });
+  return temp.innerHTML;
+}
```
Comment (thecodrr) [inline apps/web/src/utils/md.ts:36]: What is this for?

Comment (01zulfi) [reply apps/web/src/utils/md.ts:36]: `snarkdown` wasn't adding `target=_blank` to `a` tags, so I'm using this function to achieve that

**Review by thecodrr — APPROVED** [review]
