### PR TITLE
Fix bug report confirmation dialog width and scroll

### LINKED ISSUE #5559: "Thank you for reporting" dialog cuts out text
The dialog/modal that comes up after reporting an issue is small. Same size as the "Report and issue" dialog/modal, which would be okay except the text within the "thank you ..." one doesn't wrap, making it difficult to read and to navigate to read (tiny horizontal scroll bar).

**Device information:**
App version: 3.0.2-c9a8134-web
OS: OS X 10.15.7
Browser: Safari 17.4.1
Pro: true

### PR DESCRIPTION
**Pull request by Parthiv-M**
- EDIT: Previously, the message returned a string enclosed in `` with fixed spacing/new lines. This has been changed to be concatenated with `+` s so that a ```<p />``` is generated instead of a `pre` which was causing the fixed width and ugly scroll issue
- Fixes #5559

### CODE REVIEW

**Comment by thecodrr** [comment]
This makes no sense. \`\` doesn't produce `pre` tag. It's just used for string substitution. Changing it to "" doesn't make a difference. Have you actually tested this change?

File: apps/web/src/dialogs/issue-dialog.tsx [hunk 1]
```diff
@@ -150,11 +150,11 @@ function showIssueReportedDialog({ url }: { url: string }) {
...
-    message: `You can track your bug report at [${url}](${url}).
-    
-    Please note that we will respond to your bug report on the link above. **We recommended that you save the above link for later reference.**
-    
-    If your issue is critical (e.g. notes not syncing, crashes etc.), please [join our Discord community](https://discord.com/invite/zQBK97EE22) for one-to-one support.`
+    message: "You can track your bug report at [" + url + "](" + url + ")."
+
+      + "\n\n<br />Please note that we will respond to your bug report on the link above. **We recommended that you save the above link for later reference.**"
+
+      + "\n\n<br />If your issue is critical (e.g. notes not syncing, crashes etc.), please [join our Discord community](https://discord.com/invite/zQBK97EE22) for one-to-one support."
```
Comment (thecodrr) [inline apps/web/src/dialogs/issue-dialog.tsx:157]: This is unnecessary. The pre tag is created due to the indentation. Just remove that and it'll work.

To add empty line breaks in Markdown, use `\\` instead of `<br>`.

**Comment by Parthiv-M** [comment]
> This makes no sense. `` doesn't produce `pre` tag. It's just used for string substitution. Changing it to "" doesn't make a difference. Have you actually tested this change?

Yep, it worked in my tests (locally). But I'll make the indentation change nevertheless.

**Comment by Parthiv-M** [comment]
Hi, I realised that the way I interpreted the change was wrong, rather than the usage of backticks itself. The code that fixed it was the concatenation of strings rather than removing interpolation altogether. 

I have reverted back to using backticks but concatenated them instead of giving fixed spacing. 

My apologies for the confusion. I have attached a screenshot of the result and updated the PR description too.

bug_report

File: apps/web/src/dialogs/issue-dialog.tsx [hunk 2]
```diff
@@ -150,11 +150,9 @@ function showIssueReportedDialog({ url }: { url: string }) {
...
     title: "Thank you for reporting!",
     positiveButtonText: "Copy link",
-    message: `You can track your bug report at [${url}](${url}).
-    
-    Please note that we will respond to your bug report on the link above. **We recommended that you save the above link for later reference.**
-    
-    If your issue is critical (e.g. notes not syncing, crashes etc.), please [join our Discord community](https://discord.com/invite/zQBK97EE22) for one-to-one support.`
+    message: `You can track your bug report at [${url}](${url}).`
+      + `\n\nPlease note that we will respond to your bug report on the link above. **We recommended that you save the above link for later reference.**`
+      + `\n\nIf your issue is critical (e.g. notes not syncing, crashes etc.), please [join our Discord community](https://discord.com/invite/zQBK97EE22) for one-to-one support.`
```
Comment (thecodrr) [inline apps/web/src/dialogs/issue-dialog.tsx:155]:
```suggestion
    message: `You can track your bug report at [${url}](${url}).

\
Please note that we will respond to your bug report on the link above. **We recommended that you save the above link for later reference.**

\
If your issue is critical (e.g. notes not syncing, crashes etc.), please [join our Discord community](https://discord.com/invite/zQBK97EE22) for one-to-one support.`
```

**Comment by thecodrr** [comment]
Thanks!
