### PR TITLE
web: fix restore notebooks over limit for free users (#6812)

### LINKED ISSUE #6812: Notebooks & Subnotebooks
Hi, has the number of notebooks a free user can make increased from 3? And does the number of subnotebooks a free user can make have a limit? Sorry, I'm genuinely not sure if this is a bug I'm experiencing.

Currently, I have 3 notebooks and 17 subnotebooks. When I tried making a new subnotebook, it tells me that I already need to subscribe to the Pro plan/version to add more notebooks. I deleted some subnotebooks and tried making new notebooks and I was able to have more than 3 notebooks. I was able to add more notebooks as long as I deleted some subnotebooks. Is the limit for subnotebooks and notebooks combined to 20?

Also, I checked the trash and tried to see what would happen if I restored the deleted notebooks and subnotebooks despite the limit and it all got restored. It seems like the limit of 3 notebooks (based on what was stated) was bypassed because I was able to restore more than 5 notebooks despite the limit that's been written. The only thing I couldn't do was add new notebooks and/or subnotebooks. I even tested what would happen if I kept making new notebooks and/or subnotebooks and kept deleting them then restoring them. I figured that all of those notebooks and subnotebooks could be restored despite the limit. It's just that I can't make new ones until I repeat the process.

_______________
**Device information:**
App version: 3.0.20
Platform: android
Device: samsung-SM-A225F-13
Pro: false
Logged in: yes

### PR DESCRIPTION
**Pull request by 01zulfi**
Closes #6812

### CODE REVIEW

File: packages/core/src/collections/trash.ts [hunk 1]
```diff
@@ -192,6 +197,12 @@ export default class Trash {
     }
 
     if (notebookIds.length > 0) {
+      const canRestoreNotebooks =
+        (await this.db.notebooks.all.count()) >= FREE_NOTEBOOKS_LIMIT &&
```
Comment (thecodrr) [inline packages/core/src/collections/trash.ts:201]: This'll only work prevent restoration if the notebooks length exactly matches `FREE_NOTEBOOKS_LIMIT` but what if user has 10 deleted notebooks in trash and 12 notebooks otherwise? After restoration, the user will have a total of 22 notebooks (2 more than allowed).

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: packages/core/src/collections/trash.ts (hunk 1 above)
Comment (01zulfi) [reply packages/core/src/collections/trash.ts]: Nice catch! I've included `notebookIds.length` in the check, hope that caters to this case

File: packages/core/src/collections/trash.ts [hunk 2]
```diff
@@ -192,6 +197,13 @@ export default class Trash {
     }
 
     if (notebookIds.length > 0) {
+      const cannotRestoreNotebooks =
+        (await this.db.notebooks.all.count()) + notebookIds.length >
+          FREE_NOTEBOOKS_LIMIT &&
+        !(await checkIsUserPremium(CHECK_IDS.notebookAdd));
+      if (cannotRestoreNotebooks) {
```
Comment (thecodrr) [inline packages/core/src/collections/trash.ts:204]: I think this would be more readable as:

```
if (notebooksLimitReached and !checkIsUserPremium)
```

**Review by thecodrr — CHANGES_REQUESTED** [review]

**Review by thecodrr — APPROVED** [review]
