### PR TITLE
Fix notes list visibility  #6294

### LINKED ISSUE #6294: Bug?
Appears to be a bug with your app the app frequently opens showing a note instead of the list of notes.  Default set to show notes on opening but very annoying

---

**Device information:**
App version: 3.0.12
Platform: android
Device: OnePlus-ONEPLUS A6013-11
Pro: true
Logged in: yes

### PR DESCRIPTION
**Pull request by SahilAslam001**
https://github.com/user-attachments/assets/e49d9b45-3c55-4802-bb46-8d1e3ed33ba1

## Description
Appears to be a bug with your app the app frequently opens showing a note instead of the list of notes. Default set to show notes on opening but very annoying fix now the app open from the list everytime 
closes #6294
## Type of Change
- [x] Bug fix
- [ ] Feature

## Visuals
- [x] Attached relevant screenshots / screen recording / GIF
- [ ] N/A (not a feature or no UI changes)

## Testing
- [ ] Ran all E2E tests
- [ ] Ran all integration tests
- [ ] Added/updated tests for this change (if needed)
- [x] N/A (tests not needed — explanation provided below)

## Platform

- [ ] Web
- [x] Mobile
- [ ] Desktop

## Sign-off
- [ ] QA passed
- [ ] UI/UX passed

### CODE REVIEW

**Comment by ammarahm-ed** [comment]
@SahilAslam001 rebase with master to remove unrelated commits.

```
git rebase master
git push --force
```

**Comment by ammarahm-ed** [comment]
This fixes the issue by trying to removing AppState data however does not take care of not setting AppState in the first place which would completely address the problem. Remember that this was an app feature where it reloads the editor if app was killed in background. If we are removing it, we need to address the removal properly.

File: apps/mobile/app/hooks/use-app-events.tsx [hunk 1]
```diff
@@ -861,7 +863,7 @@ export const useAppEvents = () => {
           eSendEvent(eEditorReset);
         }
       } else {
-        await saveEditorState();
+        // await saveEditorState();
```
Comment (ammarahm-ed) [inline apps/mobile/app/hooks/use-app-events.tsx]: Why not remove the statement instead of just commenting it out?

**Review by ammarahm-ed — CHANGES_REQUESTED** [review]
This still does not address the problem completely. All places in the app where app state is being saved or unset need to be removed since we are removing this feature from our app. This includes anything on the JS side + on native side.

File: apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/OnClearFromRecentService.java
Comment (ammarahm-ed) [inline apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/OnClearFromRecentService.java]: We can remove this service as it does not serve any purpose after these changes and remove all instances where this is being used on android

File: apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java [hunk 2]
```diff
@@ -95,17 +95,13 @@ public void setSecureMode(final boolean mode) {
...
     public void setAppState(final String appState) {
-        SharedPreferences appStateDetails = getReactApplicationContext().getSharedPreferences("appStateDetails", Context.MODE_PRIVATE);
-        SharedPreferences.Editor edit = appStateDetails.edit();
-        edit.putString("appState", appState);
-        edit.apply();
+        
     }
 
     @ReactMethod(isBlockingSynchronousMethod = true)
     public String getAppState() {
```
Comment (ammarahm-ed) [inline apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java]: Remove these functions since they are empty now. Also remove them in `NotesnookModule` on JavaScript side.

File: apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java [hunk 3]
```diff
@@ -95,17 +95,13 @@ public void setSecureMode(final boolean mode) {
 
     @ReactMethod
     public void setAppState(final String appState) {
```
Comment (ammarahm-ed) [inline apps/mobile/android/app/src/main/java/com/streetwriters/notesnook/RCTNNativeModule.java]: Remove this function

File: apps/mobile/app/screens/editor/tiptap/utils.ts [hunk 4]
```diff
@@ -157,18 +157,12 @@ export function getAppState() {
     if (canRestoreAppState(appState)) {
       return appState;
     } else {
-      clearAppState();
       return null;
     }
   }
   return null;
 }
```
Comment (ammarahm-ed) [inline apps/mobile/app/screens/editor/tiptap/utils.ts:165]: All above code is also not needed anymore since it's also related to AppState. We can also remove the `AppState` type since it's not needed anymore.

File: apps/mobile/android/app/src/main/AndroidManifest.xml [hunk 5]
```diff
@@ -200,7 +200,6 @@
         </activity>
 
         <service
-            android:name=".OnClearFromRecentService"
             android:enabled="true"
             android:exported="true"
             android:stopWithTask="false" />
```
Comment (ammarahm-ed) [inline apps/mobile/android/app/src/main/AndroidManifest.xml]: Remove this service entry. Just removing `android:name` is not enough here.

**Review by ammarahm-ed — APPROVED** [review]
