### PR TITLE
web: fix nav menu collapse

### LINKED ISSUE #7393: Subfolder bug
Subfolders no longer work. Impossible to display them

**Device information:**
App version: 3.0.24-21e1e73-web
OS: OS X 10.15.7 64-bit
Browser: Chrome 131.0.0.0
Pro: true

### PR DESCRIPTION
**Pull request by luis-411**
Fixes: #7335

This should also fix #7393 since the same functionality is used when toggeling the subnotebook folder.

### CODE REVIEW

File: apps/web/src/components/split-pane/index.tsx [hunk 1]
```diff
@@ -96,14 +96,15 @@ export const SplitPane = React.forwardRef<
   const wrapSize = useRef(0);
   const childrenLength = childrenToArray(children).length;
   const autoSaveKey = autoSaveId ? `csp:${autoSaveId}` : undefined;
+  const previousSize = useRef(0);
```
Comment (thecodrr) [inline apps/web/src/components/split-pane/index.tsx:99]: The naming could be improved.

```suggestion
  const lastCollapsedPaneSize = useRef(0);
```

**Review by thecodrr — APPROVED** [review]
