### PR TITLE
editor: fixed-code-highlights not applying

### LINKED ISSUE #2222: Syntax highlighting for code blocks?
### What happened?

You can select a type/language in the code blocks.

Assuming thats for syntax highlighting then its not working. Text stays the same in any case.

### Steps to reproduce the problem

Add a code block, try different types.

### Version

2.4.9

### Platform/OS

Android

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Abdulrehman-Jafer**
Fixes #2222

### CODE REVIEW

**Comment by thecodrr** [comment]
@Abdulrehman-Jafer editor tests are failing.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 1]
```diff
@@ -198,7 +205,20 @@ export function HighlighterPlugin({
...
+              const isRegistered = () => {
+                for (const key in registeredLanguage) {
+                  const currentLang = registeredLanguage[key];
+                  if (currentLang == language) {
+                    return true;
+                  }
+                }
+              };
+
+              if (!isRegistered()) {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:219]: Why not just use `refractor.registered`?

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 2]
```diff
@@ -221,8 +241,6 @@ export function HighlighterPlugin({
                   decorations = decorations.remove(toRemove);
                 if (toAdd.length > 0)
                   decorations = decorations.add(tr.doc, toAdd);
-              } else {
-                languages[id] = language;
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:225]: Why are you flipping the `if` statement? We don't do negative checks in the if statement if possible.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 3]
```diff
@@ -121,10 +121,17 @@ export function HighlighterPlugin({
...
+          const registeredLanguage = refractor.listLanguages();
           if (!pluginState) return;
 
           const changedBlocks: Set<string> = new Set();
           for (const blockKey in pluginState.languages) {
+            if (pluginLanguages) {
+              if (!registeredLanguage.includes(pluginLanguages[blockKey])) {
+                HIGHLIGHTED_BLOCKS.delete(blockKey);
+              }
+            }
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:134]: Simplify this and merge it with the if statement below. You might need to move the `if..statement` a few downs lower.

**Review by thecodrr — CHANGES_REQUESTED** [review]
This solution might work but needs fixes. Also please add tests for this.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 2 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:225]: Ok I will flip it back and it will make more sense.

**Comment by Abdulrehman-Jafer** [comment]
I can pass the editor test by changing line 205 from  return "No need to register"; to return false this will pass the test but it will call the update method useless until there is no language selected for the block.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 4]
```diff
@@ -198,7 +196,16 @@ export function HighlighterPlugin({
               updated.add(block.pos);
 
               const { id, language } = block.node.attrs;
-              if (languages[id]) {
+
+              const isRegistered = () => {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:200]: No need for this function.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 5]
```diff
@@ -198,7 +196,16 @@ export function HighlighterPlugin({
...
+                if (language) {
+                  return refractor.registered(language) ? true : false;
+                }
+                return "No need to register";
+                // If I return false It will uselessly calls the update method until the language in null(plaintext).
+              };
+
+              if (isRegistered()) {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:208]: I am not sure this is correct.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 6]
```diff
@@ -124,24 +124,22 @@ export function HighlighterPlugin({
           if (!pluginState) return;
 
           const changedBlocks: Set<string> = new Set();
-          for (const blockKey in pluginState.languages) {
-            if (HIGHLIGHTED_BLOCKS.has(blockKey)) continue;
 
+          for (const blockKey in pluginState.languages) {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:128]: Why this change?

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 7]
```diff
@@ -124,24 +124,22 @@ export function HighlighterPlugin({
...
             if (!languageDefinition) continue;
 
-            if (refractor.registered(language)) {
-              if (!HIGHLIGHTED_BLOCKS.has(blockKey)) {
-                HIGHLIGHTED_BLOCKS.add(blockKey);
-                changedBlocks.add(blockKey);
-              }
-              continue;
-            }
-
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:144]: Why is this removed?

**Review by thecodrr — CHANGES_REQUESTED** [review]
Not ready yet.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 4 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:200]: Ok

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 6 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:128]: I did not change this line. Its the same.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 7 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:144]: This is unnecessary now as we are already checking if the language is registered in the top if statement.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 6 above)
Comment (thecodrr) [reply packages/editor/src/extensions/code-block/highlighter.ts:128]: Why is it showing in the diff?

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 7 above)
Comment (thecodrr) [reply packages/editor/src/extensions/code-block/highlighter.ts:144]: What about everything inside that if block?

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 6 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:128]: It is some kind of glitch probab it is not showing in the diff in my view.

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 8]
```diff
@@ -121,18 +121,18 @@ export function HighlighterPlugin({
         },
         async update(view) {
           const pluginState = HIGHLIGHTER_PLUGIN_KEY.getState(view.state);
-          const pluginLanguages = pluginState?.languages;
-          const registeredLanguage = refractor.listLanguages();
           if (!pluginState) return;
 
           const changedBlocks: Set<string> = new Set();
+
           for (const blockKey in pluginState.languages) {
```
Comment (Abdulrehman-Jafer) [inline packages/editor/src/extensions/code-block/highlighter.ts:128]: same

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 6 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:128]: OK.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 7 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:144]: I will add it back my bad It was a mistake.

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 5 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: I am sure sir.

**Comment by Abdulrehman-Jafer** [comment]
Still returning "No need to register" which I think is enhancing performance. But if this not feel right to you I can remove it,

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 9]
```diff
@@ -198,6 +203,15 @@ export function HighlighterPlugin({
               updated.add(block.pos);
 
               const { id, language } = block.node.attrs;
+
+              const isRegistered =
+                language ? refractor.registered(language) ? true : false : "No need to register"
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:208]: You are still pointlessly doing this instead of just `refractor.registered`.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: packages/editor/src/extensions/code-block/highlighter.ts (hunk 9 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: OK I am removing it right now.

Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: Actually no I checked this check is necessary because when new code block is created language is null so that is why I am doing this check.

Comment (thecodrr) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: If language is null, `refractor.registered` will return false, no?

Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: It gives error.
type error

Comment (thecodrr) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: Then just do `language && refractor.registered(language)`

Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/highlighter.ts:208]: Ok

File: packages/editor/src/extensions/code-block/highlighter.ts [hunk 10]
```diff
@@ -198,6 +203,15 @@ export function HighlighterPlugin({
               updated.add(block.pos);
 
               const { id, language } = block.node.attrs;
+
+              const isRegistered =
+                language && refractor.registered(language) ? true : false;
+
+              if (!isRegistered) {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/highlighter.ts:210]:
```suggestion
              if (language && !refractor.registered(language)) {
```

**Comment by thecodrr** [comment]
@Abdulrehman-Jafer you need to add tests for this.

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts [hunk 11]
```diff
@@ -191,3 +192,28 @@ test("editing code in a highlighted code block should not be too slow", async ()
...
+    defaultLanguage: "plaintext"
+  });
+  editor.commands.updateAttributes(CodeBlock.name, { language: "java" });
+  await new Promise((resolve) => setTimeout(resolve, 100));
+
+  const highlighterState = plugin.spec.state?.init(editor.state, editor.state);
+  const highlighterLanguages = highlighterState?.languages;
+  for (const key in highlighterLanguages) {
+    const isTrue = refractor.registered(highlighterLanguages[key]);
+    expect(isTrue).toBe(true);
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/tests/code-block.test.ts:217]: This should be a single line or rename the `isTrue` to `isRegistered`.

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts [hunk 12]
```diff
@@ -191,3 +192,28 @@ test("editing code in a highlighted code block should not be too slow", async ()
...
+
+  const plugin = HighlighterPlugin({
+    name: CodeBlock.name,
+    defaultLanguage: "plaintext"
+  });
+  editor.commands.updateAttributes(CodeBlock.name, { language: "java" });
+  await new Promise((resolve) => setTimeout(resolve, 100));
+
+  const highlighterState = plugin.spec.state?.init(editor.state, editor.state);
+  const highlighterLanguages = highlighterState?.languages;
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/tests/code-block.test.ts:214]: This is not necessary. You can just check that `java` or whatever the language you switched to is registered.

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts [hunk 13]
```diff
@@ -191,3 +192,28 @@ test("editing code in a highlighted code block should not be too slow", async ()
...
+    initialContent: CODEBLOCKS_HTML,
+    extensions: {
+      codeblock: CodeBlock
+    }
+  });
+
+  const plugin = HighlighterPlugin({
+    name: CodeBlock.name,
+    defaultLanguage: "plaintext"
+  });
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/tests/code-block.test.ts:209]: Not needed in this test.

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts [hunk 14]
```diff
@@ -191,3 +192,28 @@ test("editing code in a highlighted code block should not be too slow", async ()
   expect(timings.reduce((a, b) => a + b) / timings.length).toBeLessThan(16);
   expect(editorElement.outerHTML).toMatchSnapshot();
 });
+
+test("Switching codeblock language should register the new language", async () => {
```
Comment (thecodrr) [inline packages/editor/src/extensions/code-block/tests/code-block.test.ts:196]: Are we just checking that language got registered? Shouldn't we also check that the code also got highlighted?

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts (hunk 11 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/tests/code-block.test.ts:217]: OK

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts (hunk 14 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/tests/code-block.test.ts:196]: The problem we solved here was the languages were not being registered which was the root cause of the code not being hghlighted so that is why I made the test to only check for new language registeration

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts (hunk 12 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/tests/code-block.test.ts:214]: Ok understood

File: packages/editor/src/extensions/code-block/tests/code-block.test.ts (hunk 13 above)
Comment (Abdulrehman-Jafer) [reply packages/editor/src/extensions/code-block/tests/code-block.test.ts:209]: Ok

**Review by thecodrr — APPROVED** [review]

**Review by Abdulrehman-Jafer — COMMENTED** [review]
This will regenerate the other bug that I solved which was language was not applying when user create a new Block and select a language for the first time and user had to select the language for second time to select the language. After debugging I found out that the reason of it was the first time codeblock id was undefined.

**Comment by thecodrr** [comment]
@Abdulrehman-Jafer 

> This will regenerate the other bug that I solved which was language was not applying when user create a new Block and select a language for the first time and user had to select the language for second time to select the language. After debugging I found out that the reason of it was the first time codeblock id was undefined.

That's why tests are important.

**Review by thecodrr — APPROVED** [review]
