### PR TITLE
web: add support for toggling spellcheck per note

### LINKED ISSUE #6549: Spell checker doesn't work on Android
### What happened?

The spell checker doesn't work in Notesnook in Android.

### Steps to reproduce the problem

1. Spell some words wrong.
2. There are no red squiggle lines indicating words that are misspelled.

## Screenshot
pic1

## Logs
App logs from Android are posted below.

## System info
* OS: Android 14/GrapheneOS
* Device: Pixel 5a (`barbet`)
* App store used: Droid-ify/F-Droid

### Version

v3.0.16

### Platform/OS

Android

### Relevant log output

```shell
type: logcat
osVersion: google/barbet/barbet:14/AP2A.240805.005/2024090400:user/release-keys
packageName: com.streetwriters.notesnook:15133
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of crash
09-10 10:03:47.742 19419 19454 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 19454 (create_react_co), pid 19419 (iters.notesnook)
09-10 10:03:48.139 19460 19460 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-10 10:03:48.139 19460 19460 F DEBUG   : Build fingerprint: 'google/barbet/barbet:14/AP2A.240805.005/2024090400:user/release-keys'
09-10 10:03:48.139 19460 19460 F DEBUG   : Revision: 'MP1.0'
09-10 10:03:48.139 19460 19460 F DEBUG   : ABI: 'arm64'
09-10 10:03:48.139 19460 19460 F DEBUG   : Timestamp: 2024-09-10 06:03:47.804907600-0400
09-10 10:03:48.139 19460 19460 F DEBUG   : Process uptime: 2s
09-10 10:03:48.139 19460 19460 F DEBUG   : Cmdline: com.streetwriters.notesnook
09-10 10:03:48.139 19460 19460 F DEBUG   : pid: 19419, tid: 19454, name: create_react_co  >>> com.streetwriters.notesnook <<<
09-10 10:03:48.139 19460 19460 F DEBUG   : uid: 10208
09-10 10:03:48.139 19460 19460 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000010
09-10 10:03:48.139 19460 19460 F DEBUG   : Cause: null pointer dereference
09-10 10:03:48.139 19460 19460 F DEBUG   :     x0  0000d49ab19602a0  x1  b400d52e77f59c40  x2  0000d49ab1962e80  x3  b400d52e77f59c20
09-10 10:03:48.139 19460 19460 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000d49ab19765c8  x7  0000000000000000
09-10 10:03:48.139 19460 19460 F DEBUG   :     x8  0000000000000000  x9  0000000000000001  x10 0000000000000002  x11 fffffffffffffffc
09-10 10:03:48.139 19460 19460 F DEBUG   :     x12 0000000000000004  x13 b400d4dd3d138244  x14 00000000fffffffc  x15 0000d49ab1962e18
09-10 10:03:48.139 19460 19460 F DEBUG   :     x16 0000d49ab1975f98  x17 0000d7c8e9d591e0  x18 0000d49ab34dc000  x19 0000000000000000
09-10 10:03:48.139 19460 19460 F DEBUG   :     x20 0000d49ab1956a54  x21 0000000000000000  x22 b400d52e77f59c40  x23 0000000000000010
09-10 10:03:48.139 19460 19460 F DEBUG   :     x24 0000d49ab3bec858  x25 b400d4abcf42f660  x26 b400d4bf12d12420  x27 b400d52e77f59c20
09-10 10:03:48.139 19460 19460 F DEBUG   :     x28 0000000000000002  x29 0000d49ab3bec250
09-10 10:03:48.139 19460 19460 F DEBUG   :     lr  0000d49ab195ac48  sp  0000d49ab3bec250  pc  0000d49ab195fd14  pst 0000000080001000
09-10 10:03:48.139 19460 19460 F DEBUG   : 19 total frames
09-10 10:03:48.139 19460 19460 F DEBUG   : backtrace:
09-10 10:03:48.139 19460 19460 F DEBUG   :       #00 pc 000000000000fd14  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/base.apk (offset 0xa93000) (ffi_prep_closure_loc+88)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #01 pc 000000000000ac44  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/base.apk (offset 0xa93000) (Java_com_sun_jna_Native_registerMethod+1132)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #02 pc 0000000000dd5788  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (art_jni_trampoline+328)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #03 pc 0000000000dd4b7c  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.sun.jna.Native.register+3484)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #04 pc 0000000001887c90  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (org.libsodium.rn.RCTSodiumModule.<init>+688)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #05 pc 00000000017e0930  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (org.libsodium.rn.g.createNativeModules+160)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #06 pc 000000000072f274  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.d0.b+404)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #07 pc 0000000000749194  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.k.b+148)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #08 pc 00000000007056bc  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.processPackage+604)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #09 pc 0000000000705ce0  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.processPackages+1168)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #10 pc 00000000007001e0  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.createReactContext+1072)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #11 pc 0000000000702c70  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2+1616)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #12 pc 00000000007c4d5c  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.w.run+108)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #13 pc 000000000014f978  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: e6ec81391fdbe5c39f39efb5706eda591561c0ff)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #14 pc 00000000003a4374  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #15 pc 00000000003415f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #16 pc 000000000049ce78  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1720) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #17 pc 00000000000767ac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 10fdb0947eaa74439a0f73593b6b2b84)
09-10 10:03:48.139 19460 19460 F DEBUG   :       #18 pc 0000000000067d50  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 10fdb0947eaa74439a0f73593b6b2b84)
09-10 10:03:55.296 19513 19547 F libc    : Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10 in tid 19547 (create_react_co), pid 19513 (iters.notesnook)
09-10 10:03:55.590 19554 19554 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-10 10:03:55.590 19554 19554 F DEBUG   : Build fingerprint: 'google/barbet/barbet:14/AP2A.240805.005/2024090400:user/release-keys'
09-10 10:03:55.590 19554 19554 F DEBUG   : Revision: 'MP1.0'
09-10 10:03:55.590 19554 19554 F DEBUG   : ABI: 'arm64'
09-10 10:03:55.590 19554 19554 F DEBUG   : Timestamp: 2024-09-10 06:03:55.367752833-0400
09-10 10:03:55.590 19554 19554 F DEBUG   : Process uptime: 2s
09-10 10:03:55.590 19554 19554 F DEBUG   : Cmdline: com.streetwriters.notesnook
09-10 10:03:55.590 19554 19554 F DEBUG   : pid: 19513, tid: 19547, name: create_react_co  >>> com.streetwriters.notesnook <<<
09-10 10:03:55.590 19554 19554 F DEBUG   : uid: 10208
09-10 10:03:55.591 19554 19554 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0000000000000010
09-10 10:03:55.591 19554 19554 F DEBUG   : Cause: null pointer dereference
09-10 10:03:55.591 19554 19554 F DEBUG   :     x0  0000c4f9883dc2a0  x1  b400c58b15726a60  x2  0000c4f9883dee80  x3  b400c58b15726a40
09-10 10:03:55.591 19554 19554 F DEBUG   :     x4  0000000000000000  x5  0000000000000000  x6  0000c4f9883f25c8  x7  0000000000000000
09-10 10:03:55.591 19554 19554 F DEBUG   :     x8  0000000000000000  x9  0000000000000001  x10 0000000000000002  x11 fffffffffffffffc
09-10 10:03:55.591 19554 19554 F DEBUG   :     x12 0000000000000004  x13 b400c53a65619ec4  x14 00000000fffffffc  x15 0000c4f9883dee18
09-10 10:03:55.591 19554 19554 F DEBUG   :     x16 0000c4f9883f1f98  x17 0000c81c593431e0  x18 0000c4f98b75c000  x19 0000000000000000
09-10 10:03:55.591 19554 19554 F DEBUG   :     x20 0000c4f9883d2a54  x21 0000000000000000  x22 b400c58b15726a60  x23 0000000000000010
09-10 10:03:55.591 19554 19554 F DEBUG   :     x24 0000c4f98bf71628  x25 b400c50b7f404af0  x26 b400c51aef130880  x27 b400c58b15726a40
09-10 10:03:55.591 19554 19554 F DEBUG   :     x28 0000000000000002  x29 0000c4f98bf71020
09-10 10:03:55.591 19554 19554 F DEBUG   :     lr  0000c4f9883d6c48  sp  0000c4f98bf71020  pc  0000c4f9883dbd14  pst 0000000080001000
09-10 10:03:55.591 19554 19554 F DEBUG   : 19 total frames
09-10 10:03:55.591 19554 19554 F DEBUG   : backtrace:
09-10 10:03:55.591 19554 19554 F DEBUG   :       #00 pc 000000000000fd14  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/base.apk (offset 0xa93000) (ffi_prep_closure_loc+88)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #01 pc 000000000000ac44  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/base.apk (offset 0xa93000) (Java_com_sun_jna_Native_registerMethod+1132)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #02 pc 0000000000dd5788  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (art_jni_trampoline+328)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #03 pc 0000000000dd4b7c  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.sun.jna.Native.register+3484)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #04 pc 0000000001887c90  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (org.libsodium.rn.RCTSodiumModule.<init>+688)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #05 pc 00000000017e0930  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (org.libsodium.rn.g.createNativeModules+160)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #06 pc 000000000072f274  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.d0.b+404)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #07 pc 0000000000749194  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.k.b+148)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #08 pc 00000000007056bc  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.processPackage+604)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #09 pc 0000000000705ce0  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.processPackages+1168)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #10 pc 00000000007001e0  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.createReactContext+1072)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #11 pc 0000000000702c70  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.ReactInstanceManager.lambda$runCreateReactContextOnNewThread$2+1616)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #12 pc 00000000007c4d5c  /data/app/~~5Nz_h3Iw4vvLFns07og28w==/com.streetwriters.notesnook-ixbQpUuSogn24-ADnSqvrA==/oat/arm64/base.odex (com.facebook.react.w.run+108)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #13 pc 000000000014f978  /system/framework/arm64/boot.oat (java.lang.Thread.run+72) (BuildId: e6ec81391fdbe5c39f39efb5706eda591561c0ff)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #14 pc 00000000003a4374  /apex/com.android.art/lib64/libart.so (art_quick_invoke_stub+612) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #15 pc 00000000003415f0  /apex/com.android.art/lib64/libart.so (art::ArtMethod::Invoke(art::Thread*, unsigned int*, unsigned int, art::JValue*, char const*)+144) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #16 pc 000000000049ce78  /apex/com.android.art/lib64/libart.so (art::Thread::CreateCallback(void*)+1720) (BuildId: a9c91dd566de9629d6d56b55352b5518)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #17 pc 00000000000767ac  /apex/com.android.runtime/lib64/bionic/libc.so (__pthread_start(void*)+204) (BuildId: 10fdb0947eaa74439a0f73593b6b2b84)
09-10 10:03:55.591 19554 19554 F DEBUG   :       #18 pc 0000000000067d50  /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64) (BuildId: 10fdb0947eaa74439a0f73593b6b2b84)
--------- beginning of events
09-13 15:37:11.968  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:11.970  9505  9505 I wm_on_paused_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performPause,time=1ms]
09-13 15:37:12.350  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Not drawing due to not visible]
09-13 15:37:12.475  9505  9505 I wm_on_stop_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=2ms]
09-13 15:37:12.924  9505  9505 I wm_on_restart_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performRestart,time=0ms]
09-13 15:37:12.924  9505  9505 I wm_on_start_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=handleStartActivity,time=0ms]
09-13 15:37:12.928  9505  9505 I wm_on_resume_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=RESUME_ACTIVITY,time=3ms]
09-13 15:37:12.928  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topWhenResuming]
09-13 15:37:12.954  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Start draw after previous draw not visible]
09-13 15:37:12.985  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:37:14.945  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=80,Unix Time Ns=1726241834944481s,Elapsed Time Ns=617972719013.935s,Uptime Ns=341149808411.294s,Tag=0@0@com.streetwriters.notesnook]
09-13 15:37:15.050  9505  9889 I jank_cuj_events_end_request: [CUJ Type=80,Unix Time Ns=1726241835050044s,Elapsed Time Ns=617972824163.373s,Uptime Time Ns=341149913559.117s]
09-13 15:37:15.537  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:15.540  9505  9505 I wm_on_paused_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performPause,time=1ms]
09-13 15:37:15.658  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=81,Unix Time Ns=1726241835658515s,Elapsed Time Ns=617973432638.85s,Uptime Ns=341150522035.636s,Tag=1@0@com.streetwriters.notesnook]
09-13 15:37:15.673  9505  9889 I jank_cuj_events_cancel_request: [CUJ Type=81,Unix Time Ns=1726241835672967s,Elapsed Time Ns=617973447089.268s,Uptime Time Ns=341150536485.846s]
09-13 15:37:15.673  9505  9889 I jank_cuj_events_end_request: [CUJ Type=81,Unix Time Ns=1726241835673053s,Elapsed Time Ns=617973447172.185s,Uptime Time Ns=341150536568.502s]
09-13 15:37:15.945  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Not drawing due to not visible]
09-13 15:37:15.960  9505  9505 I wm_on_stop_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=2ms]
09-13 15:37:16.506  9505  9505 I wm_on_restart_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performRestart,time=0ms]
09-13 15:37:16.507  9505  9505 I wm_on_start_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=handleStartActivity,time=0ms]
09-13 15:37:16.510  9505  9505 I wm_on_resume_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=RESUME_ACTIVITY,time=3ms]
09-13 15:37:16.510  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topWhenResuming]
09-13 15:37:16.525  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Start draw after previous draw not visible]
09-13 15:37:16.544  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:37:16.657  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=80,Unix Time Ns=1726241836657257s,Elapsed Time Ns=617974431379.991s,Uptime Ns=341151520776.621s,Tag=0@0@com.streetwriters.notesnook]
09-13 15:37:16.774  9505  9889 I jank_cuj_events_end_request: [CUJ Type=80,Unix Time Ns=1726241836774278s,Elapsed Time Ns=617974548396.409s,Uptime Time Ns=341151637792.101s]
09-13 15:37:28.293  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:29.073  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:29.458  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=81,Unix Time Ns=1726241849458240s,Elapsed Time Ns=617987232358.454s,Uptime Ns=341164321754.355s,Tag=1@0@com.streetwriters.notesnook]
09-13 15:37:29.518  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:37:29.570  9505  9889 I jank_cuj_events_end_request: [CUJ Type=81,Unix Time Ns=1726241849570738s,Elapsed Time Ns=617987344855.809s,Uptime Time Ns=341164434251.553s]
09-13 15:37:33.943  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=80,Unix Time Ns=1726241853943521s,Elapsed Time Ns=617991717643.484s,Uptime Ns=341168807040.114s,Tag=0@0@com.streetwriters.notesnook]
09-13 15:37:34.053  9505  9889 I jank_cuj_events_end_request: [CUJ Type=80,Unix Time Ns=1726241854053673s,Elapsed Time Ns=617991827796.672s,Uptime Time Ns=341168917193.406s]
09-13 15:37:44.428  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=81,Unix Time Ns=1726241864428186s,Elapsed Time Ns=618002202305.414s,Uptime Ns=341179291701.94s,Tag=1@0@com.streetwriters.notesnook]
09-13 15:37:44.539  9505  9889 I jank_cuj_events_end_request: [CUJ Type=81,Unix Time Ns=1726241864539161s,Elapsed Time Ns=618002313280.269s,Uptime Time Ns=341179402676.221s]
09-13 15:37:54.035  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:54.751  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:58.899  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:37:58.901  9505  9505 I wm_on_paused_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performPause,time=1ms]
09-13 15:37:59.300  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Not drawing due to not visible]
09-13 15:37:59.305  9505  9505 I wm_on_stop_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=1ms]
09-13 15:38:26.587  9505  9505 I wm_on_restart_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performRestart,time=0ms]
09-13 15:38:26.587  9505  9505 I wm_on_start_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=handleStartActivity,time=0ms]
09-13 15:38:26.589  9505  9505 I wm_on_resume_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=RESUME_ACTIVITY,time=2ms]
09-13 15:38:26.590  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topWhenResuming]
09-13 15:38:26.620  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Start draw after previous draw not visible]
09-13 15:38:26.656  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:38:39.638  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:38:40.010  9505  9505 I wm_on_paused_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performPause,time=2ms]
09-13 15:38:40.268  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Not drawing due to not visible]
09-13 15:38:40.276  9505  9505 I wm_on_stop_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=0ms]
09-13 15:38:42.303  9505  9505 I wm_on_restart_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performRestart,time=0ms]
09-13 15:38:42.303  9505  9505 I wm_on_start_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=handleStartActivity,time=1ms]
09-13 15:38:42.306  9505  9505 I wm_on_resume_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=RESUME_ACTIVITY,time=2ms]
09-13 15:38:42.306  9505  9505 I wm_on_top_resumed_gained_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topWhenResuming]
09-13 15:38:42.326  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=Start draw after previous draw not visible]
09-13 15:38:42.337  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:38:45.334  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=80,Unix Time Ns=1726241925333858s,Elapsed Time Ns=618063107977.054s,Uptime Ns=341240197373.111s,Tag=0@0@com.streetwriters.notesnook]
09-13 15:38:45.448  9505  9889 I jank_cuj_events_end_request: [CUJ Type=80,Unix Time Ns=1726241925448673s,Elapsed Time Ns=618063222797.118s,Uptime Time Ns=341240312194.008s]
09-13 15:38:46.821  9505  9889 I jank_cuj_events_begin_request: [CUJ Type=81,Unix Time Ns=1726241926821018s,Elapsed Time Ns=618064595136.89s,Uptime Ns=341241684532.843s,Tag=1@0@com.streetwriters.notesnook]
09-13 15:38:46.936  9505  9889 I jank_cuj_events_end_request: [CUJ Type=81,Unix Time Ns=1726241926936895s,Elapsed Time Ns=618064711016.641s,Uptime Time Ns=341241800413.115s]
09-13 15:38:51.268  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:39:01.360  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:39:04.966  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:39:06.305  9505  9505 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
09-13 15:39:14.936  9505  9505 I wm_on_top_resumed_lost_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=topStateChangedWhenResumed]
09-13 15:39:15.501  9505  9505 I wm_on_paused_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performPause,time=11ms]
09-13 15:39:15.508  9505  9505 I wm_on_stop_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=1ms]
09-13 15:39:15.525  9505  9505 I wm_on_destroy_called: [Token=154844285,Component Name=com.streetwriters.notesnook.MainActivity,Reason=performDestroy,time=14ms]

description: Try to figure out spell check
```

### PR DESCRIPTION
**Pull request by 01zulfi**
Signed-off-by: 01zulfi <85733202+01zulfi@users.noreply.github.com>

Closes #6549

### CODE REVIEW

File: packages/core/src/database/migrations.ts [hunk 1]
```diff
@@ -392,6 +392,19 @@ export class NNMigrationProvider implements MigrationProvider {
...
+        async up(db) {
+          await db.schema
+            .alterTable("notes")
+            .addColumn("spellcheck", "boolean")
+            .execute();
+          await db
+            .updateTable("notes")
+            .set({ spellcheck: true })
+            .where("spellcheck", "is", null)
+            .execute();
```
Comment (thecodrr) [inline packages/core/src/database/migrations.ts]: Why not use default column value?

**Review by thecodrr — APPROVED** [review]
This looks really good.

cc @ammarahm-ed please add this in the mobile apps.

File: packages/core/src/database/migrations.ts (hunk 1 above)
Comment (01zulfi) [reply packages/core/src/database/migrations.ts]: just added the default column value: `true`

this is a data migration for setting `spellcheck: true` for all previous notes. I forgot to comment yesterday on this and how should the data migration be handled

Comment (thecodrr) [reply packages/core/src/database/migrations.ts]: This shouldn't be required since SQLite will automatically set the default value for newly added column.

Comment (01zulfi) [reply packages/core/src/database/migrations.ts]: done, removed the unnecessary migration

File: apps/web/src/stores/note-store.ts [hunk 2]
```diff
@@ -94,6 +95,16 @@ class NoteStore extends BaseStore<NoteStore> {
...
   };
 
+  spellcheck = async (state: boolean, ...ids: string[]) => {
+    await db.notes.spellcheck(state, ...ids);
+    await this.refresh();
+
+    AppEventManager.publish(AppEvents.spellcheckUpdated, {
+      noteIds: ids,
+      spellcheck: state
+    });
```
Comment (thecodrr) [inline apps/web/src/stores/note-store.ts]: Why are we sending an event? Why not just reload all the editor sessions and take the `spellcheck` value from the session note?

File: apps/web/src/components/note/index.tsx [hunk 3]
```diff
@@ -403,6 +405,16 @@ export const noteMenuItems: (
...
+    {
+      type: "button",
+      key: "spellcheck",
+      title: strings.spellCheck(),
+      isChecked: note.spellcheck,
+      icon: SpellCheck.path,
+      isHidden: IS_DESKTOP_APP && !useSpellChecker.getState().enabled,
+      onClick: () => store.spellcheck(!note.spellcheck, ...ids),
+      multiSelect: true
+    },
```
Comment (thecodrr) [inline apps/web/src/components/note/index.tsx]: I think this setting should only be available from inside the editor. Maybe in the status bar or in the properties panel. No point putting this here as it'll probably only be used via the editor.

File: apps/web/src/components/editor/index.tsx [hunk 4]
```diff
@@ -356,7 +356,7 @@ function EditorView({
       <div className="dialogContainer" />
       <Editor
         id={session.id}
-        nonce={1}
+        nonce={session.nonce}
```
Comment (01zulfi) [inline apps/web/src/components/editor/index.tsx]: I'm refreshing the sessions by incrementing `nonce`. I had to replace the hardcoded `nonce={1}` here for the session refresh to work. Just wanted to highlight this
