### PR TITLE
web: command palette fixes

### LINKED ISSUE #7666: Searching in the command palette causes styling bugs
### What happened?

- [ ] When searching for a recent command, the style code becomes visible. 

Image

- [ ] ~~Headings are searchable(is this a bug?).~~ Also the heading capitalization for "Recent" changes when matching letters.

Image

### Steps to reproduce the problem

Search for a recent command in the command palette.
Search for the word "recent".

### Version

3.0.28-00250c6-web

### Platform/OS

Firefox

### Relevant log output

```shell

```

### LINKED ISSUE #7667: Executing a failed search in the command palette or quick open menu crashes app
### What happened?

Searching for a string that does not return any results and pressing enter causes the app to crash. Same error occurs in both command palette and quick open.

Image

### Steps to reproduce the problem

Search for a string that returns no results.

### Version

3.0.28-00250c6-web

### Platform/OS

Firefox

### Relevant log output

```shell
h is undefined
onKeyDown@https://app.notesnook.com/assets/app-D-3-GnP3J2jH.js:206:61987
xI@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:9855
EI@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:10009
_I@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:10066
ug@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:31446
f7@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:31865
h2/<@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:36778
E6@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:293:36935
D9@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:8991
h2@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:33152
J3@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:17362
$I@https://app.notesnook.com/assets/root-BRUvyIlaax7M.js:290:17144
```

### PR DESCRIPTION
**Pull request by 01zulfi**
* core: add getIdentifier in fuzzy; this allows the caller to provide a custom indentifier instead of relying on id field in the items list
* fix crashing when hitting enter when no results found
* fix commands list not refreshing when removing recent command
* fix recent command not showing up in the commands list
* fix searched commands showing up under wrong group label

Closes #7666 
Closes #7667

### CODE REVIEW

File: packages/core/src/utils/fuzzy.ts [hunk 1]
```diff
@@ -20,9 +20,10 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 import { match, surround } from "fuzzyjs";
 import { clone } from "./clone";
 
-export function fuzzy<T extends { id: string }>(
+export function fuzzy<T>(
   query: string,
   items: T[],
+  getIdentifier: (item: T) => string,
```
Comment (01zulfi) [inline packages/core/src/utils/fuzzy.ts:26]: The first bug highlighted here https://github.com/streetwriters/notesnook/issues/7666 happens because the `id` of recent and default commands match, and it gets incorrectly identified as the same command by `fuzzy`. I've added a `getIdentifier` param to fix this. Not sure if this is the best fix

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx [hunk 2]
```diff
@@ -529,3 +531,27 @@ function getCommandPaletteHelp(isCommandMode: boolean) {
...
+    }
+    const index = sortedWrtGroups.findIndex((c) => c[0].group === group);
+    if (index === -1) {
+      sortedWrtGroups.push([command]);
+    } else {
+      sortedWrtGroups[index].push(command);
+    }
+  }
+  return recent.concat(sortedWrtGroups.flat());
+}
```
Comment (thecodrr) [inline apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:557]: You can just `.sort` by `group` instead of this custom logic.

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx [hunk 3]
```diff
@@ -69,10 +69,9 @@ export const CommandPaletteDialog = DialogManager.register(
 
     const commands = usePromise(async () => {
       select(0);
-      if (!defaultCommands.current)
-        defaultCommands.current = await getDefaultCommands();
+      defaultCommands.current = await getDefaultCommands();
```
Comment (thecodrr) [inline apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:72]: Why this change? We don't want to get default commands over and over again.

File: apps/web/src/dialogs/command-palette/commands.ts [hunk 4]
```diff
@@ -234,7 +234,9 @@ export async function getDefaultCommands(): Promise<Command[]> {
 }
 
 export function getCommandById(id: string): Command | undefined {
-  return staticCommands.find((command) => command.id === id);
+  return staticCommands
+    .concat(getEditorCommands())
+    .find((command) => command.id === id);
```
Comment (thecodrr) [inline apps/web/src/dialogs/command-palette/commands.ts:239]: Don't concat. Just search separately. It'll be more efficient.

**Review by thecodrr — CHANGES_REQUESTED** [review]

**Comment by thecodrr** [comment]
@01zulfi I think in future we should create separate PRs for each fix. That way the fixes can be cherry picked instead of merging it in bulk.

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx (hunk 3 above)
Comment (01zulfi) [reply apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:73]: We need the `getDefaultCommands` to re-run after a recent is removed from the user. Thanks for pointing this out, I realized we can add
```ts
defaultCommands.current = await getDefaultCommands()
``` 
in the click handler to fix this, instead of the above change

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx (hunk 2 above)
Comment (01zulfi) [reply apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:559]: I'm facing a challenge where `.sort` respects the order of the searched elements, need to figure this out

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx (hunk 3 above)
Comment (thecodrr) [reply apps/web/src/dialogs/command-palette/command-palette-dialog.tsx]: Good idea.

File: apps/web/src/dialogs/command-palette/command-palette-dialog.tsx (hunk 2 above)
Comment (thecodrr) [reply apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:559]: Were you able to figure something out? If not, we can keep this I think.

Comment (01zulfi) [reply apps/web/src/dialogs/command-palette/command-palette-dialog.tsx:559]: Nope

**Review by thecodrr — APPROVED** [review]
