### PR TITLE
web: changes related to table of contents (#4977)

### LINKED ISSUE #4977: Table of contents feature improvements for web editor
### What problem are you facing?

I'm so happy to have an outline / table of contents. I heavily rely on headings for hierarchy of my notes so this feature is very well appreciated. Being able to easily navigate large notes is nice. However, the implementation isn't the most useful. 

### What's the solution you'd like to see in Notesnook?

 I think these three changes would make this feature much more useful for everyone. 

- [ ] A single button below the top-right menu to expand and collapse the ToC
The ToC should be below this menu so that the menu is still accessible.

- [ ] Visibility should be statefull, so it will always be in the state last used
Because I use this feature a lot, I would prefer if the ToC was always visible. Currently I need to open it every time I start Notesnook. Then if I want to access the menu in the top right, I need to close it. 

- [ ] Increase the indentation so the hierarchy is easier to see
I think the indent should be two or three times as much.

Here's what these changes might look like:
collapsed
expanded

### What alternatives have you considered?

_No response_

### Additional context

Additional interactions: Focus Mode should not hide the ToC. Disable Editor Margins should remove margins, but only up to the ToC (if it is expanded). 

- [ ] Bonus points for making the ToC width adjustable. I love how much flexibility the sidebar and notes frames have. 

The iOS ToC has appropriate indentation.

### LINKED ISSUE #6711: Table of Contents covers note contents
### What happened?

If you open the table of contents, the side panel covers the note contents. Instead, the contents should re-wrap to the smaller open editing window so that you can still edit the note with the table of contents open.

### Steps to reproduce the problem

1. Create a new note.
2. Insert some random long lines of text.
3. Open the table of contents.
4. Create a new line and keep typing - the line will go under the table of contents and you cannot see what you are typing.

### Version

3.0.18-5f0d14f-desktop

### Platform/OS

Linux

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by 01zulfi**
* move toc button out of action bar into fixed position
* adjust editor width based on toc state
* save toc state in local storage
* increase indentation in toc

Signed-off-by: Zulfiqar Ali <85733202+01zulfi@users.noreply.github.com>

Closes #4977 
Closes #6711

### CODE REVIEW

File: apps/web/src/components/editor/action-bar.tsx
Comment (thecodrr) [inline apps/web/src/components/editor/action-bar.tsx:1]: I think moving the TOC button is unnecessary. Let's undo that.

File: apps/web/src/components/editor/table-of-contents.tsx [hunk 1]
```diff
@@ -102,10 +104,10 @@ function TableOfContents(props: TableOfContentsProps) {
         display: "flex",
         position: "absolute",
         right: 0,
-        top: TITLE_BAR_HEIGHT,
+        top: 32,
```
Comment (thecodrr) [inline apps/web/src/components/editor/table-of-contents.tsx:107]: Why this change?

File: apps/web/src/components/editor/index.tsx [hunk 2]
```diff
@@ -624,9 +625,15 @@ function EditorChrome(props: PropsWithChildren<EditorProps>) {
...
+            alignSelf: [
+              "stretch",
+              focusMode ? "center" : "stretch",
+              !editorMargins ? (isTOCVisible ? "stretch" : "center") : "center"
+            ],
             maxWidth: editorMargins ? "min(100%, 850px)" : "auto",
-            width: "100%"
+            width: isTOCVisible
+              ? `calc(100% - ${TABLE_OF_CONTENTS_WIDTH}px)`
+              : "100%"
```
Comment (thecodrr) [inline apps/web/src/components/editor/index.tsx:636]: I don't think this is the best way to do this. Instead of altering the width of the editor, we can render the TableOfContents to the right of the editor. That way it'll automatically resize when TOC becomes visible.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: apps/web/src/components/editor/table-of-contents.tsx (hunk 1 above)
Comment (01zulfi) [reply apps/web/src/components/editor/table-of-contents.tsx]: `TITLE_BAR_HEIGHT` is 0 for web and since I moved the TOC a little below, I had to give some value to `top`. But now TOC isn't in absolute position but rather rendered to the right of editor. Hence, I've reverted this change as not needed anymore.

File: apps/web/src/components/editor/table-of-contents.tsx [hunk 3]
```diff
@@ -49,6 +49,8 @@ import { useEditorManager } from "./manager";
 import { TITLE_BAR_HEIGHT } from "../title-bar";
 import { strings } from "@notesnook/intl";
 
+export const TABLE_OF_CONTENTS_WIDTH = 300;
+
```
Comment (thecodrr) [inline apps/web/src/components/editor/table-of-contents.tsx:53]: This isn't needed anymore.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: apps/web/src/components/editor/index.tsx [hunk 4]
```diff
@@ -152,7 +152,12 @@ export default function TabsView() {
                 ) : session.type === "conflicted" || session.type === "diff" ? (
                   <DiffViewer session={session} />
                 ) : (
-                  <MemoizedEditorView session={session} />
+                  <Flex sx={{ overflow: "hidden" }}>
+                    <MemoizedEditorView session={session} />
+                    {isTOCVisible && activeSessionId && (
+                      <TableOfContents sessionId={activeSessionId} />
+                    )}
+                  </Flex>
```
Comment (thecodrr) [inline apps/web/src/components/editor/index.tsx:160]: Instead of wrapping this in its own Flex, we should move the TOC to its own Panel. That way it'll become automatically resizeable.

File: apps/web/src/components/editor/table-of-contents.tsx
Comment (thecodrr) [inline apps/web/src/components/editor/table-of-contents.tsx:1]: 2 things:

1. Let's get rid of the opening/closing animation on TableOfContents.
2. Instead of showing the Back arrow icon for closing the TOC, we should show a Cross button on the right side.

**Review by thecodrr — CHANGES_REQUESTED** [review]
Just some final changes. Everything else looks good.

**Review by thecodrr — APPROVED** [review]

File: apps/web/src/components/editor/index.tsx [hunk 5]
```diff
@@ -204,14 +204,17 @@ export default function TabsView() {
               </Panel>
             </>
           )}
+
+          {isTOCVisible && activeSessionId && (
+            <Panel order={3} defaultSize={30}>
```
Comment (thecodrr) [inline apps/web/src/components/editor/index.tsx:209]: You need to add `PanelResizeHandle` otherwise it won't resize. Also set `defaultSize` to 25 and minSize to 15. It looks too big. You'll also need to add an `id` prop to the handle otherwise the `order` doesn't work.

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: apps/web/src/components/editor/index.tsx (hunk 5 above)
Comment (01zulfi) [reply apps/web/src/components/editor/index.tsx]: Add `id` prop to `Panel` or `PanelResizeHandle`. I've added `id` to `Panel` as it is in other panels in the component. Let me know if we want to add to `PanelResizeHandle` as well

Comment (thecodrr) [reply apps/web/src/components/editor/index.tsx]: I don't think adding it to `PanelResizeHandle` is necessary.

**Review by thecodrr — APPROVED** [review]
