### PR TITLE
mobile: fix notes title edit issue

### LINKED ISSUE #8437: Annoyance / possible bug
Not sure if bug but please fix the need to double delete a note title.  Easy to recreate go into any note delete the existing title for example in order to put a new one in and bam it auto inserts date time so have to delete again .  App should recognise that if I delete a title it's because I'm going to put a new one

_______________
**Device information:**
App version: 3.2.10
Platform: android
Device: samsung-SM-S936B-15
Pro: false
Logged in: yes

### PR DESCRIPTION
**Pull request by SahilAslam001**
## Description

https://github.com/user-attachments/assets/81a0bf00-8b0a-4b9e-bb45-23a692fa3aa6

Not sure if bug but please fix the need to double delete a note title. Easy to recreate go into any note delete the existing title for example in order to put a new one in and bam it auto inserts date time so have to delete again . App should recognise that if I delete a title it's because I'm going to put a new one

closes #8437

## Type of Change
- [x] Bug fix
- [ ] Feature

## Visuals
- [x] Attached relevant screenshots / screen recording / GIF
- [ ] N/A (not a feature or no UI changes)

## Testing
- [ ] Ran all E2E tests
- [ ] Ran all integration tests
- [ ] Added/updated tests for this change (if needed)
- [x] N/A (tests not needed — explanation provided below)

## Platform

- [ ] Web
- [x] Mobile
- [ ] Desktop

## Sign-off
- [x] QA passed
- [x] UI/UX passed

### CODE REVIEW

**Comment by ammarahm-ed** [comment]
Let's not make changes to `packages/core`. Instead simply check if the existing note has title before saving and if it has a title, we can skip updating the title value in editor.

File: packages/core/src/collections/notes.ts [hunk 1]
```diff
@@ -162,8 +162,9 @@ export class Notes implements ICollection {
           currentNoteTitleFields?.title !== headlineTitle
         ) {
           item.title = titleFormat.replace(HEADLINE_REGEX, headlineTitle);
-        } else if (item.title === "")
+        } else if (item.title === "") {
```
Comment (ammarahm-ed) [inline packages/core/src/collections/notes.ts]:
```suggestion
        } else if (item.title === "")
```

File: packages/core/src/collections/notes.ts [hunk 2]
```diff
@@ -162,8 +162,9 @@ export class Notes implements ICollection {
...
           item.title = currentNoteTitleFields?.title || "Untitled";
+        }
```
Comment (ammarahm-ed) [inline packages/core/src/collections/notes.ts]:
```suggestion
```
