### PR TITLE
monograph: remove callout headings from toc (#6875)

### LINKED ISSUE #6875: Callouts break Monograph Table of Contents
### What happened?

Image

### Steps to reproduce the problem

Add any callout and publish monograph.

Example: https://monogr.ph/663a0adf06e91ea603c31037/

### Version

Latest monograph

### Platform/OS

Linux, Chrome/Chromium, Firefox, Android

### Relevant log output

```shell

```

### PR DESCRIPTION
**Pull request by 01zulfi**
Signed-off-by: 01zulfi <85733202+01zulfi@users.noreply.github.com>

Closes #6875

### CODE REVIEW

**Comment by 01zulfi** [comment]
Are you talking about this specific approach or the code changes? Did you have something else in mind?

**Comment by thecodrr** [comment]
@01zulfi I am talking about the changes _and_ the approach. I don't think I can come up with a more complicated way to do this.

File: apps/monograph/app/components/monographpost/index.tsx [hunk 1]
```diff
@@ -90,6 +90,13 @@ function generateTableOfContents() {
         : level;
     currentHeading = headingLevel;
 
+    const isCalloutHeading =
+      !heading.previousSibling &&
+      heading.parentElement?.classList.contains("callout");
+    if (isCalloutHeading) {
+      continue;
+    }
+
```
Comment (01zulfi) [inline apps/monograph/app/components/monographpost/index.tsx:99]: Please let me know if this can be improved

File: apps/monograph/app/components/monographpost/index.tsx [hunk 2]
```diff
@@ -90,6 +90,13 @@ function generateTableOfContents() {
         : level;
     currentHeading = headingLevel;
 
+    const isCalloutHeading =
+      !heading.previousSibling &&
```
Comment (thecodrr) [inline apps/monograph/app/components/monographpost/index.tsx:94]: Why this check?

File: apps/monograph/app/components/monographpost/index.tsx [hunk 3]
```diff
@@ -90,6 +90,13 @@ function generateTableOfContents() {
...
+      heading.parentElement?.classList.contains("callout");
+    if (isCalloutHeading) {
```
Comment (thecodrr) [inline apps/monograph/app/components/monographpost/index.tsx:96]: You should do this at the very start of the loop.

File: apps/monograph/app/components/monographpost/index.tsx [hunk 4]
```diff
@@ -90,6 +90,13 @@ function generateTableOfContents() {
         : level;
     currentHeading = headingLevel;
 
+    const isCalloutHeading =
+      !heading.previousSibling &&
+      heading.parentElement?.classList.contains("callout");
```
Comment (thecodrr) [inline apps/monograph/app/components/monographpost/index.tsx:95]: Why not do `heading.closest('.callout');`?

Read more about `closest` here: https://developer.mozilla.org/en-US/docs/Web/API/Element/closest

**Review by thecodrr — CHANGES_REQUESTED** [review]

File: apps/monograph/app/components/monographpost/index.tsx (hunk 2 above)
Comment (01zulfi) [reply apps/monograph/app/components/monographpost/index.tsx:94]: If I don't use this check, the user defined headings inside callout aren't added to the toc

Comment (thecodrr) [reply apps/monograph/app/components/monographpost/index.tsx:94]: We don't want any headings inside a callout to appear in TOC.

File: apps/monograph/app/components/monographpost/index.tsx (hunk 3 above)
Comment (01zulfi) [reply apps/monograph/app/components/monographpost/index.tsx:96]: If we move this to the start of the loop, heading levels aren't respected for headings inside callout. 

Check at start of loop: 
image


Otherwise:
image

File: apps/monograph/app/components/monographpost/index.tsx (hunk 2 above)
Comment (01zulfi) [reply apps/monograph/app/components/monographpost/index.tsx:94]: ah, got it. I misunderstood then.

File: apps/monograph/app/components/monographpost/index.tsx (hunk 3 above)
Comment (01zulfi) [reply apps/monograph/app/components/monographpost/index.tsx:96]: ^ ignore

File: apps/monograph/app/components/monographpost/index.tsx [hunk 5]
```diff
@@ -90,6 +90,11 @@ function generateTableOfContents() {
         : level;
     currentHeading = headingLevel;
 
+    const isCalloutHeading = heading.closest(".callout");
+    if (isCalloutHeading) {
```
Comment (thecodrr) [inline apps/monograph/app/components/monographpost/index.tsx:94]: This should be at the start of the loop.

**Review by thecodrr — CHANGES_REQUESTED** [review]

**Review by thecodrr — APPROVED** [review]
